### ISSUE TITLE
Thanks for your valueable works. And my questions is "Is this repo implement the OpenPCDet version SESSD?"

### ISSUE THREAD

**Issue by EmiyaNing** [RunpeiDong/PointDistiller#1]
In your preprint paper, I see that you have compared your work with 'SESSD'.  And I also try to re-implement the 'SESSD' based on OpenPCDet. But there seem many problems in my re-implement versions, so I could not re-produce its result.  Therefore, I am very interested in the SESSD you repo have implemented, and I hope the code can be open-sourced as soon as possible

**Comment by RunpeiDong** [comment]
Hi @[EmiyaNing](https://github.com/EmiyaNing),

Thanks for your comments. We are happy to release the codes as soon as possible after the reviewing process is done. 
Regarding the great previous work 'SESSD', I suppose you may encounter complicated problems like bugs with OpenPCDet. I suggest you try to contact OpenPCDet or the authors of 'SESSD' for a solution.
