### ISSUE TITLE
i found that  SECOND teacher model has low AP .

### ISSUE THREAD

**Issue by c122-ode** [RunpeiDong/PointDistiller#11]
hello,
 i use the checkpoint hv_second_secfpn_6x8_80e_kitti-3d-3class_20200620_230238-9208083a.pth 
 both v1.0.0rc v1.0.0r2

**Comment by c122-ode** [comment]
also point-rcnn  teacher model.

**Comment by RunpeiDong** [comment]
This is normal. The checkpoints of our teacher model were downloaded from the mmdetection3d GitHub. The detection accuracy of these models themselves is normal and reasonable. However, during an update of mmdetection3d, the model structure files of mmdetection3d were uniformly modified, which led to the previous models being unable to infer normally to achieve good results. However, this does not mean that the mAP of these teacher models themselves is low; they were just used incorrectly. Please refer to https://github.com/open-mmlab/mmdetection3d/issues/1339 for more details. Currently, we recommend that you find the latest version of the teacher model weights from mmdetection3d for distillation.

**Comment by c122-ode** [comment]
Thank you!

**Comment by RunpeiDong** [comment]
You are welcome.
