### ISSUE TITLE
When will open source code

### ISSUE THREAD

**Issue by AnnieYu0401** [RunpeiDong/PointDistiller#2]
Hi, I would like to know when the source code will open.

**Comment by RunpeiDong** [comment]
Hi @AnnieYu0401,

Thanks for your comments. We currently plan to open source our codes after the review process.

**Comment by Ryze0124** [comment]
Today is 20221123 🤣

**Comment by RunpeiDong** [comment]
> Today is 20221123 🤣

Yet our paper is still not accepted by any conference.:) 
We are working on it to make it more solid.
