### ISSUE TITLE
When will open source code

### ISSUE THREAD

**Issue by guwen007** [RunpeiDong/PointDistiller#4]

**Comment by RunpeiDong** [comment]
Hi @guwen007,

Thanks for your interest in our work. 

Sorry for the delay. The code will be available soon when we have prepared and released the camera-ready version.

**Comment by jumptiger66** [comment]
Hello ,  Does this paper be accepted by CVPR 2023 ?

**Comment by RunpeiDong** [comment]
Hi @jumptiger66,

Thanks for your interest. 

Yes, this paper is accepted to appear at CVPR 2023.

**Comment by jumptiger66** [comment]
Congratulations , it is an amazing work !
