### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by DezeZhao** [RunpeiDong/PointDistiller#5]
Hi! Congratulations! when will you open source the codes? Looking forward to it!

**Comment by RunpeiDong** [comment]
Hi @DezeZhao,

Thanks for your interest in our work! I'm a bit busy recently with ongoing projects and submissions. I will finish the code cleaning job and release it by this month.

**Comment by PleasantPhoenix** [comment]
> Hi @DezeZhao,
> 
> Thanks for your interest in our work! I'm a bit busy recently with ongoing projects and submissions. I will finish the code cleaning job and release it by this month.

Hello, thank you for your contribution. Are you sure you plan to release the code in April?

**Comment by RunpeiDong** [comment]
Code is released. 

Sorry for the delay. My right hand finger was injured which made me hard to work.
