### ISSUE TITLE
Importance score for points

### ISSUE THREAD

**Issue by charmeleonz** [RunpeiDong/PointDistiller#6]
Hi, thanks for the work. Just wondering what the values in Fig. 3(b) actually denote? (e.g. [0.3, 0.2 0.1, ...], from which 0.3 is taken)

**Comment by RunpeiDong** [comment]
Hi @charmeleonz,

Thanks for your interest.

- The vectors in Fig. 3(b) middle denote `per-point features`, e.g., [0.3, 0.2, 0.1, ...].
- The values in Fig. 3(b) right denote the value after `max_pooling`, which is used as the importance score, e.g., 0.3 is the max pooled value of the example feature vector.

Hope this could help you.

**Comment by charmeleonz** [comment]
So why can the max pooled value be used as an importance score?

**Comment by RunpeiDong** [comment]
@charmeleonz,

- Feature saliency as importance measurement is an effective and widely adopted practice in image-based KD methods or other areas, this inspires us to transfer this strategy;
- Intuitively, the feature with a higher value may indicate more significant attention to scene understanding for the network, which aligns with the sparse nature of point clouds;
- For 3D point clouds, max-pooling is an effective method to obtain permutation-invariant features, which is very important for geometry understanding.
- For a more detailed understanding, please refer to the paper.

**Comment by charmeleonz** [comment]
@RunpeiDong Thanks!
